"""Alter Catch and Expedition relationships.

Revision ID: e219462f2d78
Revises: 7a40c207ff83
Create Date: 2024-11-22 02:13:38.723198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e219462f2d78'
down_revision = '7a40c207ff83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expedition_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_catches_expedition_id_expeditions'), 'expeditions', ['expedition_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_catches_expedition_id_expeditions'), type_='foreignkey')
        batch_op.drop_column('expedition_id')

    # ### end Alembic commands ###
