"""Remove unused model.

Revision ID: eec5085b2a2b
Revises: e219462f2d78
Create Date: 2024-11-29 08:09:10.776801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec5085b2a2b'
down_revision = 'e219462f2d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokedexes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokedexes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_pokedexes_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pokedexes')
    )
    # ### end Alembic commands ###
