"""Initial migration.

Revision ID: 3c19616452d6
Revises: 
Create Date: 2024-10-23 17:06:57.287366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c19616452d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions'))
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dex_number', sa.Integer(), nullable=False),
    sa.Column('shiny', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_species'))
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_types'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('catches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caught_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_catches_species_id_species')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_catches_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catches'))
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_table('locales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_locales_region_id_regions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locales'))
    )
    op.create_table('pokedexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pokedexes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokedexes'))
    )
    op.create_table('pokemon_types',
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], name=op.f('fk_pokemon_types_species_id_species')),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], name=op.f('fk_pokemon_types_type_id_types'))
    )
    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('locale_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locale_id'], ['locales.id'], name=op.f('fk_expeditions_locale_id_locales')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_expeditions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expeditions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expeditions')
    op.drop_table('pokemon_types')
    op.drop_table('pokedexes')
    op.drop_table('locales')
    op.drop_table('goals')
    op.drop_table('catches')
    op.drop_table('users')
    op.drop_table('types')
    op.drop_table('species')
    op.drop_table('regions')
    # ### end Alembic commands ###
