"""Change constraints for locales for uniqueness.

Revision ID: 7a40c207ff83
Revises: 27cca22d353c
Create Date: 2024-11-01 16:56:28.372795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a40c207ff83'
down_revision = '27cca22d353c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.create_unique_constraint('_name_region_uc', ['name', 'region_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locales', schema=None) as batch_op:
        batch_op.drop_constraint('_name_region_uc', type_='unique')

    # ### end Alembic commands ###
